#spring.application.name=str-consumer

#server:
#  port: 8100
#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092

server:
  port: ${PORT:8100}
spring:
  kafka:
      bootstrap-servers: ${KAFKA_HOST:localhost:29092}